# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicinformation', '0004_auto_20170426_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicament', models.CharField(choices=[('Correct', 'Correct'), ('Wrong', 'Wrong'), ('Not decided', 'Not decided')], max_length=30)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KlassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('klas', models.ManyToManyField(to='basicinformation.klass')),
                ('user_marks', models.ManyToManyField(to='basicinformation.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('max_marks', models.IntegerField()),
                ('category', models.CharField(choices=[('1', 'Chapter 1'), ('2', 'Chapter 2'), ('3', 'Chapter 3')], max_length=100)),
                ('kl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass')),
                ('ktest', models.ManyToManyField(blank=True, to='QuestionsAndPapers.KlassTest')),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.Questions'),
        ),
    ]
