# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 21:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicinformation', '0011_auto_20170816_0246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicament', models.CharField(choices=[('Correct', 'Correct'), ('Wrong', 'Wrong'), ('Not decided', 'Not decided')], max_length=30)),
                ('text', models.TextField()),
                ('picture', models.URLField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KlassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField()),
                ('published', models.DateField(auto_now_add=True)),
                ('sub', models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English')], max_length=70)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('BodhiOnline', 'BodhiOnline'), ('BodhiSchool', 'BodhiSchool')], max_length=20)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('klas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass')),
                ('testTakers', models.ManyToManyField(to='basicinformation.Student')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('wrongAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('allAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('skippedAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('marks', models.IntegerField()),
                ('testTaken', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.KlassTest')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(choices=[('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelveth')], max_length=20)),
                ('max_marks', models.IntegerField()),
                ('sub', models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English')], max_length=70)),
                ('chapCategory', models.CharField(choices=[('1', 'Chapter 1'), ('2', 'Chapter 2'), ('3', 'Chapter 3')], max_length=30)),
                ('topic_category', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('1.10', '1.10'), ('1.11', '1.11'), ('1.12', '1.12'), ('1.13', '1.13'), ('1.14', '1.14'), ('1.15', '1.15'), ('1.16', '1.16'), ('1.17', '1.17'), ('1.18', '1.18'), ('1.19', '1.19'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.8', '2.8'), ('2.9', '2.9'), ('2.10', '2.10'), ('2.11', '2.11'), ('2.12', '2.12'), ('2.13', '2.13'), ('2.14', '2.14'), ('2.15', '2.15'), ('2.16', '2.16'), ('2.17', '2.17'), ('2.18', '2.18'), ('2.19', '2.19'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9'), ('3.10', '3.10'), ('3.11', '3.11'), ('3.12', '3.12'), ('3.13', '3.13'), ('3.14', '3.14'), ('3.15', '3.15'), ('3.16', '3.16'), ('3.17', '3.17'), ('3.18', '3.18'), ('3.19', '3.19'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.5', '4.5'), ('4.6', '4.6'), ('4.7', '4.7'), ('4.8', '4.8'), ('4.9', '4.9'), ('4.10', '4.10'), ('4.11', '4.11'), ('4.12', '4.12'), ('4.13', '4.13'), ('4.14', '4.14'), ('4.15', '4.15'), ('4.16', '4.16'), ('4.17', '4.17'), ('4.18', '4.18'), ('4.19', '4.19'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('5.4', '5.4'), ('5.5', '5.5'), ('5.6', '5.6'), ('5.7', '5.7'), ('5.8', '5.8'), ('5.9', '5.9'), ('5.10', '5.10'), ('5.11', '5.11'), ('5.12', '5.12'), ('5.13', '5.13'), ('5.14', '5.14'), ('5.15', '5.15'), ('5.16', '5.16'), ('5.17', '5.17'), ('5.18', '5.18'), ('5.19', '5.19'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('6.4', '6.4'), ('6.5', '6.5'), ('6.6', '6.6'), ('6.7', '6.7'), ('6.8', '6.8'), ('6.9', '6.9'), ('6.10', '6.10'), ('6.11', '6.11'), ('6.12', '6.12'), ('6.13', '6.13'), ('6.14', '6.14'), ('6.15', '6.15'), ('6.16', '6.16'), ('6.17', '6.17'), ('6.18', '6.18'), ('6.19', '6.19'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('7.4', '7.4'), ('7.5', '7.5'), ('7.6', '7.6'), ('7.7', '7.7'), ('7.8', '7.8'), ('7.9', '7.9'), ('7.10', '7.10'), ('7.11', '7.11'), ('7.12', '7.12'), ('7.13', '7.13'), ('7.14', '7.14'), ('7.15', '7.15'), ('7.16', '7.16'), ('7.17', '7.17'), ('7.18', '7.18'), ('7.19', '7.19'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3'), ('8.4', '8.4'), ('8.5', '8.5'), ('8.6', '8.6'), ('8.7', '8.7'), ('8.8', '8.8'), ('8.9', '8.9'), ('8.10', '8.10'), ('8.11', '8.11'), ('8.12', '8.12'), ('8.13', '8.13'), ('8.14', '8.14'), ('8.15', '8.15'), ('8.16', '8.16'), ('8.17', '8.17'), ('8.18', '8.18'), ('8.19', '8.19'), ('9.1', '9.1'), ('9.2', '9.2'), ('9.3', '9.3'), ('9.4', '9.4'), ('9.5', '9.5'), ('9.6', '9.6'), ('9.7', '9.7'), ('9.8', '9.8'), ('9.9', '9.9'), ('9.10', '9.10'), ('9.11', '9.11'), ('9.12', '9.12'), ('9.13', '9.13'), ('9.14', '9.14'), ('9.15', '9.15'), ('9.16', '9.16'), ('9.17', '9.17'), ('9.18', '9.18'), ('9.19', '9.19'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3'), ('10.4', '10.4'), ('10.5', '10.5'), ('10.6', '10.6'), ('10.7', '10.7'), ('10.8', '10.8'), ('10.9', '10.9'), ('10.10', '10.10'), ('10.11', '10.11'), ('10.12', '10.12'), ('10.13', '10.13'), ('10.14', '10.14'), ('10.15', '10.15'), ('10.16', '10.16'), ('10.17', '10.17'), ('10.18', '10.18'), ('10.19', '10.19'), ('11.1', '11.1'), ('11.2', '11.2'), ('11.3', '11.3'), ('11.4', '11.4'), ('11.5', '11.5'), ('11.6', '11.6'), ('11.7', '11.7'), ('11.8', '11.8'), ('11.9', '11.9'), ('11.10', '11.10'), ('11.11', '11.11'), ('11.12', '11.12'), ('11.13', '11.13'), ('11.14', '11.14'), ('11.15', '11.15'), ('11.16', '11.16'), ('11.17', '11.17'), ('11.18', '11.18'), ('11.19', '11.19'), ('12.1', '12.1'), ('12.2', '12.2'), ('12.3', '12.3'), ('12.4', '12.4'), ('12.5', '12.5'), ('12.6', '12.6'), ('12.7', '12.7'), ('12.8', '12.8'), ('12.9', '12.9'), ('12.10', '12.10'), ('12.11', '12.11'), ('12.12', '12.12'), ('12.13', '12.13'), ('12.14', '12.14'), ('12.15', '12.15'), ('12.16', '12.16'), ('12.17', '12.17'), ('12.18', '12.18'), ('12.19', '12.19'), ('13.1', '13.1'), ('13.2', '13.2'), ('13.3', '13.3'), ('13.4', '13.4'), ('13.5', '13.5'), ('13.6', '13.6'), ('13.7', '13.7'), ('13.8', '13.8'), ('13.9', '13.9'), ('13.10', '13.10'), ('13.11', '13.11'), ('13.12', '13.12'), ('13.13', '13.13'), ('13.14', '13.14'), ('13.15', '13.15'), ('13.16', '13.16'), ('13.17', '13.17'), ('13.18', '13.18'), ('13.19', '13.19'), ('14.1', '14.1'), ('14.2', '14.2'), ('14.3', '14.3'), ('14.4', '14.4'), ('14.5', '14.5'), ('14.6', '14.6'), ('14.7', '14.7'), ('14.8', '14.8'), ('14.9', '14.9'), ('14.10', '14.10'), ('14.11', '14.11'), ('14.12', '14.12'), ('14.13', '14.13'), ('14.14', '14.14'), ('14.15', '14.15'), ('14.16', '14.16'), ('14.17', '14.17'), ('14.18', '14.18'), ('14.19', '14.19'), ('15.1', '15.1'), ('15.2', '15.2'), ('15.3', '15.3'), ('15.4', '15.4'), ('15.5', '15.5'), ('15.6', '15.6'), ('15.7', '15.7'), ('15.8', '15.8'), ('15.9', '15.9'), ('15.10', '15.10'), ('15.11', '15.11'), ('15.12', '15.12'), ('15.13', '15.13'), ('15.14', '15.14'), ('15.15', '15.15'), ('15.16', '15.16'), ('15.17', '15.17'), ('15.18', '15.18'), ('15.19', '15.19'), ('16.1', '16.1'), ('16.2', '16.2'), ('16.3', '16.3'), ('16.4', '16.4'), ('16.5', '16.5'), ('16.6', '16.6'), ('16.7', '16.7'), ('16.8', '16.8'), ('16.9', '16.9'), ('16.10', '16.10'), ('16.11', '16.11'), ('16.12', '16.12'), ('16.13', '16.13'), ('16.14', '16.14'), ('16.15', '16.15'), ('16.16', '16.16'), ('16.17', '16.17'), ('16.18', '16.18'), ('16.19', '16.19'), ('17.1', '17.1'), ('17.2', '17.2'), ('17.3', '17.3'), ('17.4', '17.4'), ('17.5', '17.5'), ('17.6', '17.6'), ('17.7', '17.7'), ('17.8', '17.8'), ('17.9', '17.9'), ('17.10', '17.10'), ('17.11', '17.11'), ('17.12', '17.12'), ('17.13', '17.13'), ('17.14', '17.14'), ('17.15', '17.15'), ('17.16', '17.16'), ('17.17', '17.17'), ('17.18', '17.18'), ('17.19', '17.19'), ('18.1', '18.1'), ('18.2', '18.2'), ('18.3', '18.3'), ('18.4', '18.4'), ('18.5', '18.5'), ('18.6', '18.6'), ('18.7', '18.7'), ('18.8', '18.8'), ('18.9', '18.9'), ('18.10', '18.10'), ('18.11', '18.11'), ('18.12', '18.12'), ('18.13', '18.13'), ('18.14', '18.14'), ('18.15', '18.15'), ('18.16', '18.16'), ('18.17', '18.17'), ('18.18', '18.18'), ('18.19', '18.19'), ('19.1', '19.1'), ('19.2', '19.2'), ('19.3', '19.3'), ('19.4', '19.4'), ('19.5', '19.5'), ('19.6', '19.6'), ('19.7', '19.7'), ('19.8', '19.8'), ('19.9', '19.9'), ('19.10', '19.10'), ('19.11', '19.11'), ('19.12', '19.12'), ('19.13', '19.13'), ('19.14', '19.14'), ('19.15', '19.15'), ('19.16', '19.16'), ('19.17', '19.17'), ('19.18', '19.18'), ('19.19', '19.19')], max_length=10)),
                ('picture', models.URLField(blank=True, null=True)),
                ('ktest', models.ManyToManyField(blank=True, to='QuestionsAndPapers.KlassTest')),
                ('school', models.ManyToManyField(to='basicinformation.School')),
            ],
        ),
        migrations.CreateModel(
            name='SSCKlassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField()),
                ('published', models.DateField(auto_now_add=True)),
                ('sub', models.CharField(choices=[('General Intelligence', 'General Intelligence'), ('General Knowledge &        General Awareness', 'General Knowledge & General Awareness'), ('Quantitatie Analysis', 'Quantitatie Analysis'), ('English', 'English'), ('SSCMultipleSections', 'SSCMultipleSections')], max_length=70)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('BodhiOnline', 'BodhiOnline'), ('BodhiSchool', 'BodhiSchool')], max_length=20)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('klas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass')),
                ('testTakers', models.ManyToManyField(to='basicinformation.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SSCOnlineMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('wrongAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('allAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('skippedAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('marks', models.IntegerField()),
                ('testTaken', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCKlassTest')),
            ],
        ),
        migrations.CreateModel(
            name='SSCquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField(default=2)),
                ('negative_marks', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
                ('text', models.TextField()),
                ('tier_category', models.CharField(choices=[('1', 'Tier1'), ('2', 'Tier2'), ('3', 'Tier3')], max_length=20)),
                ('section_category', models.CharField(choices=[('General Intelligence', 'General Intelligence'), ('General Knowledge &        General Awareness', 'General Knowledge & General Awareness'), ('Quantitatie Analysis', 'Quantitatie Analysis'), ('English', 'English')], max_length=70)),
                ('diffculty_category', models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10, null=True)),
                ('topic_category', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('2.8', '2.8'), ('2.9', '2.9'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5'), ('3.6', '3.6'), ('3.7', '3.7'), ('3.8', '3.8'), ('3.9', '3.9'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('4.4', '4.4'), ('4.5', '4.5'), ('4.6', '4.6'), ('4.7', '4.7'), ('4.8', '4.8'), ('4.9', '4.9')], max_length=5)),
                ('picture', models.URLField(blank=True, null=True)),
                ('ktest', models.ManyToManyField(blank=True, to='QuestionsAndPapers.SSCKlassTest')),
                ('school', models.ManyToManyField(to='basicinformation.School')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryAnswerHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quests', models.IntegerField()),
                ('answers', models.IntegerField()),
                ('stud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCKlassTest')),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.Questions'),
        ),
        migrations.AddField(
            model_name='choices',
            name='sscquest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCquestions'),
        ),
    ]
