# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0004_auto_20170426_1057'),
        ('QuestionsAndPapers', '0002_klasstest_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klasstest',
            name='klas',
        ),
        migrations.AddField(
            model_name='klasstest',
            name='klas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass'),
        ),
        migrations.AlterField(
            model_name='klasstest',
            name='user_marks',
            field=models.ManyToManyField(blank=True, null=True, to='basicinformation.Student'),
        ),
    ]
