# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0003_auto_20170615_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Subject'),
        ),
    ]
