# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0004_auto_20180802_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbatchweakareas',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
