# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 13:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0005_teacher_school'),
        ('QuestionsAndPapers', '0004_auto_20170702_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('wringAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('allAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('skippedAnswers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='klasstest',
            name='user_marks',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.AddField(
            model_name='klasstest',
            name='sub',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English')], default='Maths', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klasstest',
            name='testTakers',
            field=models.ManyToManyField(to='basicinformation.Student'),
        ),
        migrations.AddField(
            model_name='questions',
            name='sub',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English')], default='Maths', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klasstest',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='onlinemarks',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.KlassTest'),
        ),
    ]
