# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0005_teacher_school'),
        ('QuestionsAndPapers', '0005_auto_20170727_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='chapCategory',
            field=models.CharField(choices=[('1', 'Chapter 1'), ('2', 'Chapter 2'), ('3', 'Chapter 3')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='school',
            field=models.ManyToManyField(to='basicinformation.School'),
        ),
    ]
