# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 08:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0007_auto_20180412_1728'),
        ('QuestionsAndPapers', '0005_auto_20180802_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWeakAreasDetailCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('cateogires', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('accuracies', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('wrong_total', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('total_total', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('averageSubjectTests', models.IntegerField(null=True)),
                ('averageDefenceTests', models.IntegerField(null=True)),
                ('normalSubjectTests', models.IntegerField(null=True)),
                ('normalDefenceTests', models.IntegerField(null=True)),
                ('testids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher')),
            ],
        ),
    ]
