# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0006_auto_20170823_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemarks',
            name='timeTaken',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssconlinemarks',
            name='timeTaken',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
