# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0006_teacherweakareasdetailcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherweakareasdetailcache',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
