# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0006_auto_20170727_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
