# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0007_teacherweakareasdetailcache_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherweakareasdetailcache',
            old_name='averageDefenceTests',
            new_name='defenceTests',
        ),
        migrations.RenameField(
            model_name='teacherweakareasdetailcache',
            old_name='averageSubjectTests',
            new_name='subjectTests',
        ),
        migrations.RemoveField(
            model_name='teacherweakareasdetailcache',
            name='normalDefenceTests',
        ),
        migrations.RemoveField(
            model_name='teacherweakareasdetailcache',
            name='normalSubjectTests',
        ),
    ]
