# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0007_auto_20170823_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryanswerholder',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
