# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0008_temporaryanswerholder_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSCansweredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('onlineMarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCOnlineMarks')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCquestions')),
            ],
        ),
    ]
