# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0009_teacherweakareasdetailcache_klass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherweakareasdetailcache',
            old_name='cateogires',
            new_name='categories',
        ),
    ]
