# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0010_auto_20170730_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemarks',
            name='testTaken',
            field=models.DateField(default=datetime.datetime(2017, 7, 30, 18, 24, 30, 226168, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
