# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0010_answeredquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprehension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sscquestions',
            name='comprehension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.Comprehension'),
        ),
    ]
