# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0011_onlinemarks_testtaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='chapCategory',
            field=models.CharField(choices=[('Chapter 1', 'Chapter 1'), ('Chapter 2', 'Chapter 2'), ('Chapter 3', 'Chapter 3')], max_length=30),
        ),
    ]
