# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 12:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0011_teacherweakareastimingcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherweakareastimingcache',
            name='timing',
        ),
        migrations.AddField(
            model_name='teacherweakareastimingcache',
            name='averagetiming',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='teacherweakareastimingcache',
            name='totalFreq',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='teacherweakareastimingcache',
            name='totalTiming',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='teacherweakareastimingcache',
            name='testids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
