# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0012_auto_20170803_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasstest',
            name='mode',
            field=models.CharField(choices=[('BodhiOnline', 'BodhiOnline'), ('BodhiSchool', 'BodhiSchool')], default='Bodhi Online', max_length=20),
            preserve_default=False,
        ),
    ]
