# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 21:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0014_auto_20170827_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssctemporaryquestionsholder',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='temporaryquestionsholder',
            name='quest',
        ),
        migrations.AddField(
            model_name='ssctemporaryquestionsholder',
            name='quests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=(0, 1), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryquestionsholder',
            name='quests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=(0, 1), size=None),
            preserve_default=False,
        ),
    ]
