# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 22:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0015_auto_20170828_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssctemporaryquestionsholder',
            name='quests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='temporaryanswerholder',
            name='answers',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='temporaryanswerholder',
            name='quests',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='temporaryquestionsholder',
            name='quests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
