# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0016_auto_20170828_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssctemporaryquestionsholder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 10, 32, 15, 961429, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
