# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-27 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0017_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.SchoolManagement'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
