# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-30 11:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0018_auto_20180827_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweakareascache',
            name='allTests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
