# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0018_auto_20170902_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=2),
        ),
    ]
