# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0019_auto_20170902_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
