# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0020_auto_20170902_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
