# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0021_auto_20170902_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='explanationPicture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sscklasstest',
            name='sub',
            field=models.CharField(choices=[('General-Intelligence', 'General-Intelligence'), ('General-Knowledge &        General-Awareness', 'General-Knowledge&General-Awareness'), ('Quantitatie-Analysis', 'Quantitatie-Analysis'), ('English', 'English'), ('SSCMultipleSections', 'SSCMultipleSections')], max_length=70),
        ),
        migrations.AlterField(
            model_name='sscquestions',
            name='section_category',
            field=models.CharField(choices=[('General-Intelligence', 'General-Intelligence'), ('General-Knowledge &        General-Awareness', 'General-Knowledge&General-Awareness'), ('Quantitatie-Analysis', 'Quantitatie-Analysis'), ('English', 'English')], max_length=70),
        ),
    ]
