# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 17:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0011_auto_20170816_0246'),
        ('QuestionsAndPapers', '0022_auto_20170903_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOneClickTestHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quests', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher')),
            ],
        ),
    ]
