# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0023_auto_20180908_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='timeEnd',
        ),
        migrations.AddField(
            model_name='timetable',
            name='timeStart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
