# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0025_auto_20171008_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscklasstest',
            name='max_marks',
            field=models.IntegerField(),
        ),
    ]
