# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0026_auto_20171023_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
