# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0011_studentdetails_email'),
        ('QuestionsAndPapers', '0028_studentaveragetimingdetailcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWeakAreasChapterCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('totalAttempted', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('totalRight', models.IntegerField()),
                ('totalWrong', models.IntegerField()),
                ('totalSkipped', models.IntegerField()),
                ('skippedPercent', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
            ],
        ),
    ]
