# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0004_auto_20180922_0103'),
        ('QuestionsAndPapers', '0030_auto_20180920_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscquestions',
            name='concepts',
            field=models.ManyToManyField(to='Recommendations.Concepts'),
        ),
    ]
