# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0030_sscteachertestresultloader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sscteachertestresultloader',
            name='onlineMarks',
        ),
        migrations.AddField(
            model_name='sscteachertestresultloader',
            name='onlineMarks',
            field=models.ManyToManyField(to='QuestionsAndPapers.SSCOnlineMarks'),
        ),
    ]
