# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 13:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0031_auto_20171212_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscteachertestresultloader',
            name='freqAnswers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
    ]
