# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0031_sscquestions_concepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('code', models.FloatField()),
            ],
        ),
    ]
