# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 10:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0032_sscteachertestresultloader_freqanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sscteachertestresultloader',
            old_name='freqAnswers',
            new_name='freqAnswersFreq',
        ),
        migrations.AddField(
            model_name='sscteachertestresultloader',
            name='freqAnswersQuestions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
    ]
