# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0032_subjectchapters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectChapters',
        ),
    ]
