# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0033_delete_subjectchapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaveragetimingdetailcache',
            name='totalAverage',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
