# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0034_sscstudentweakarealoader'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscstudentweakarealoader',
            name='lenofflineMultipleSub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sscstudentweakarealoader',
            name='lenofflineSingleSub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sscstudentweakarealoader',
            name='lenonlineMultipleSub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sscstudentweakarealoader',
            name='lenonlineSingleSub',
            field=models.IntegerField(null=True),
        ),
    ]
