# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 17:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0035_studentprogresschaptercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='rightPercent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='rightTime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='skippedPercent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='wrongPercent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='wrongTime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
