# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0035_auto_20171218_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscstudentweakarealoader',
            name='subject',
            field=models.CharField(choices=[('General-Intelligence', 'General-Intelligence'), ('General-Knowledge', 'General-Knowledge'), ('Quantitative-Analysis', 'Quantitative-Analysis'), ('English', 'English'), ('SSCMultipleSections', 'SSCMultipleSections')], max_length=70),
        ),
    ]
