# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-29 18:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0036_auto_20180925_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='totalRight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='totalSkipped',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='studentprogresschaptercache',
            name='totalWrong',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
