# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 07:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0036_auto_20171218_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sscstudentweakarealoader',
            old_name='weakTopics',
            new_name='timingTopics',
        ),
        migrations.AddField(
            model_name='sscstudentweakarealoader',
            name='weakTopicsPercentage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
    ]
