# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0013_school_logo'),
        ('QuestionsAndPapers', '0037_auto_20171219_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_difficulty', models.FloatField()),
                ('skipped_ratio', models.FloatField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCquestions')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteQuestionDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_difficulty', models.FloatField()),
                ('skipped_ratio', models.FloatField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCquestions')),
            ],
        ),
        migrations.AddField(
            model_name='sscklasstest',
            name='pattern_test',
            field=models.BooleanField(default=False),
        ),
    ]
