# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0038_auto_20180103_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscklasstest',
            name='course',
            field=models.CharField(choices=[('SSC', 'SSC'), ('Railways', 'Railways')], default='SSC', max_length=20),
        ),
    ]
