# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0040_sscklasstest_patterntestbatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscklasstest',
            name='patternTestBatches',
            field=models.ManyToManyField(blank=True, null=True, related_name='patternBatches', to='basicinformation.klass'),
        ),
    ]
