# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0013_school_logo'),
        ('QuestionsAndPapers', '0041_auto_20180105_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesused',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass'),
        ),
    ]
