# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0043_sscquestions_usedfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='dateInserted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sscquestions',
            name='dateInserted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sscquestions',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
