# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0044_auto_20180121_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscquestions',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Bi', 'Bi')], max_length=20, null=True),
        ),
    ]
