# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0045_sscquestions_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='section_category',
            field=models.CharField(choices=[('General-Intelligence', 'General-Intelligence'), ('General-Knowledge', 'General-Knowledge'), ('Quantitative-Analysis', 'Quantitative-Analysis'), ('English', 'English'), ('GroupX-English', 'GroupX-English'), ('GroupX-Physics', 'GroupX-Physics'), ('GroupX-Maths', 'GroupX-Maths')], max_length=70),
        ),
    ]
