# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-02 13:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0046_subjectrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('chapterCode', models.FloatField(blank=True, null=True)),
                ('chapterName', models.CharField(blank=True, max_length=200, null=True)),
                ('sortedAccuracies', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('students', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None)),
                ('minimumTests', models.IntegerField(blank=True, null=True)),
                ('maximumTests', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
