# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0046_auto_20180128_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='usedFor',
            field=models.CharField(blank=True, choices=[('SSC', 'SSC'), ('Aptitude', 'Aptitude'), ('Groupx', 'Groupx'), ('Groupy', 'Groupy'), ('RPSC', 'RPSC'), ('RAS', 'RAS')], max_length=30, null=True),
        ),
    ]
