# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0047_auto_20180129_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Bi', 'Bi')], default='Bi', max_length=20),
            preserve_default=False,
        ),
    ]
