# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-05 11:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0048_patterntestpattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patterntestpattern',
            old_name='subject',
            new_name='exam_name',
        ),
        migrations.RemoveField(
            model_name='patterntestpattern',
            name='chapter',
        ),
        migrations.AddField(
            model_name='patterntestpattern',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
