# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0049_auto_20180130_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprehension',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
