# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0050_comprehension_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='section_category',
            field=models.CharField(choices=[('General-Intelligence', 'General-Intelligence'), ('General-Knowledge', 'General-Knowledge'), ('Quantitative-Analysis', 'Quantitative-Analysis'), ('English', 'English'), ('Defence-English', 'Defence-English'), ('Defence-Physics', 'Defence-Physics'), ('GroupX-Maths', 'GroupX-Maths')], max_length=70),
        ),
    ]
