# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0015_teacher_subbatch'),
        ('QuestionsAndPapers', '0053_auto_20180213_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscklasstest',
            name='patternTestCreators',
            field=models.ManyToManyField(blank=True, null=True, to='basicinformation.Teacher'),
        ),
    ]
