# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0054_sscklasstest_patterntestcreators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscklasstest',
            name='patternTestCreators',
            field=models.ManyToManyField(to='basicinformation.Teacher'),
        ),
    ]
