# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0015_teacher_subbatch'),
        ('QuestionsAndPapers', '0055_auto_20180213_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCurrentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCKlassTest')),
            ],
        ),
    ]
