# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 17:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0015_teacher_subbatch'),
        ('QuestionsAndPapers', '0057_studentcurrenttest_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRankTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('totalMarks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('percentage', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('numCorrect', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('numIncorrect', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('numSkipped', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('time', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCKlassTest')),
            ],
        ),
    ]
