# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 17:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0058_testranktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='testranktable',
            name='rank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=(0, 10), size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='numCorrect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='numIncorrect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='numSkipped',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='percentage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher'),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCKlassTest'),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='testranktable',
            name='totalMarks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
    ]
