# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0061_auto_20180329_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscquestions',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sscquestions',
            name='usedFor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
