# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roll',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Administrator', 'Administrator')], default='Teacher', max_length=20),
            preserve_default=False,
        ),
    ]
