# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_userprofile_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institutionname',
            field=models.CharField(blank=True, choices=[('Kothputli', 'Kothputli'), ('Rajshree', 'Rajshree')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('9th', '9th'), ('10th', '10th')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(choices=[('School', 'School'), ('University/College', 'University/College')], default='School', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Administrator', 'Administrator')], default='Student', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rollNumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
