# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-11 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0005_firebasetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasetoken',
            name='student',
        ),
        migrations.AddField(
            model_name='firebasetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
