# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20181213_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchapters',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
