# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('pincode', models.IntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test1', models.IntegerField(blank=True, null=True)),
                ('test2', models.IntegerField(blank=True, null=True)),
                ('test3', models.IntegerField(blank=True, null=True)),
                ('hy', models.IntegerField(blank=True, null=True)),
                ('test4', models.IntegerField(blank=True, null=True)),
                ('lab1', models.IntegerField(blank=True, null=True)),
                ('lab2', models.IntegerField(blank=True, null=True)),
                ('lab3', models.IntegerField(blank=True, null=True)),
                ('finalexam', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='klass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School'),
        ),
    ]
