# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0003_auto_20170413_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prdicted_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='predicted_hy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
