# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 11:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicinformation', '0004_auto_20170426_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('confirm', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCustomProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('kl', models.CharField(blank=True, choices=[('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelveth')], max_length=10, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=200, null=True)),
                ('fullName', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.CharField(max_length=50)),
                ('numStudents', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='finalexam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hy',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='prdicted_final',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='predicted_hy',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test4',
        ),
        migrations.AddField(
            model_name='klass',
            name='level',
            field=models.CharField(blank=True, choices=[('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelveth'), ('SSC', 'SSC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(blank=True, choices=[('School', 'School'), ('SSC', 'SSC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='basicinformation.School'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subBatch',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klass', to='basicinformation.klass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherclasses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentconfirmation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass'),
        ),
        migrations.AddField(
            model_name='studentconfirmation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School'),
        ),
        migrations.AddField(
            model_name='studentconfirmation',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentconfirmation',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher'),
        ),
        migrations.AddField(
            model_name='schoolmanagement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School'),
        ),
    ]
