# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0006_klass_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='level',
            field=models.CharField(blank=True, choices=[('9', 'Ninth'), ('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelveth')], max_length=10, null=True),
        ),
    ]
