# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0007_auto_20180412_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentconfirmation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher'),
        ),
    ]
