# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0007_auto_20170727_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='basicinformation.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klass', to='basicinformation.klass'),
        ),
    ]
