# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0009_schoolmanagement_studentcustomprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('School', 'School'), ('SSC', 'SSC')], default='School', max_length=10),
            preserve_default=False,
        ),
    ]
