# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0009_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='fullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
