# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0010_studentdetails_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
