# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0011_auto_20170816_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
