# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0013_school_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='finalexam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hy',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lab3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='prdicted_final',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='predicted_hy',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='test4',
        ),
    ]
