# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-22 16:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0013_studenttesttakensubjectscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.klass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher')),
            ],
        ),
    ]
