# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-01 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0014_custombatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
