# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0014_auto_20180126_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subBatch',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
