# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0015_studentdetails_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombatch',
            name='teacher',
        ),
        migrations.AddField(
            model_name='custombatch',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='basicinformation.Teacher'),
        ),
    ]
