# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0015_teacher_subbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
