# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 08:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0017_auto_20180325_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
