# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0017_teachersubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjects',
            name='numStudents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
