# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0018_teachersubjects_numstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubjects',
            name='subject',
        ),
        migrations.AddField(
            model_name='teachersubjects',
            name='klass',
            field=models.CharField(default='SSC', max_length=50),
            preserve_default=False,
        ),
    ]
