# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0018_auto_20180328_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
