# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 08:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0019_auto_20180307_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSubjects',
            new_name='TeacherClasses',
        ),
        migrations.AddField(
            model_name='studentcustomprofile',
            name='fatherName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcustomprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcustomprofile',
            name='kl',
            field=models.CharField(blank=True, choices=[('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelveth')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
