# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0019_auto_20180328_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.CharField(max_length=50)),
                ('numStudents', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='testingcelery',
            name='student',
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='fatherName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='kl',
            field=models.CharField(blank=True, choices=[('10', 'Tenth'), ('11', 'Eleventh'), ('12', 'Twelveth')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentcustomprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TestingCelery',
        ),
    ]
