# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0021_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='code',
            field=models.CharField(default='siel', max_length=100),
            preserve_default=False,
        ),
    ]
