# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0022_auto_20181229_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAccuracyStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('rightAnswers', models.IntegerField(blank=True, null=True)),
                ('totalAttempted', models.IntegerField(blank=True, null=True)),
                ('testNumbers', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicinformation.Student')),
            ],
        ),
    ]
