# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0023_studentconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfirmation',
            name='name',
            field=models.CharField(default='siel', max_length=200),
            preserve_default=False,
        ),
    ]
