# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0024_chapteraccuracystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlogo',
            name='logo2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
