# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 09:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0025_auto_20180412_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconfirmation',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
