# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0025_subjectlogo_logo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
