# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0026_groupbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectwiseaccuracycache',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentSubjectWiseAccuracyCache',
        ),
    ]
