# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicinformation', '0016_auto_20181007_1657'),
        ('Private_Messages', '0002_auto_20180908_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='klass',
            field=models.ManyToManyField(blank=True, to='basicinformation.klass'),
        ),
    ]
