# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeexternalvideos',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
