# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionsAndPapers', '0030_auto_20180920_1909'),
        ('Recommendations', '0002_auto_20180922_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('chapter', models.FloatField(blank=True, null=True)),
                ('concept_number', models.IntegerField(blank=True, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recommendations.RecommendedContent')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionsAndPapers.SSCquestions')),
            ],
        ),
    ]
