# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0005_auto_20180922_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeExternalVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.FloatField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
