# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0006_youtubeexternalvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeexternalvideos',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeexternalvideos',
            name='chapter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeexternalvideos',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeexternalvideos',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
