# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendations', '0007_auto_20181018_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeexternalvideos',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
